version: 2
updates:
  - package-ecosystem: pip
    directory: "/modules/sopel/files"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "merge when green"
      - "dependencies"
