language: python
python:
  - "3.7"
  - "3.8"
dist: xenial
os: linux

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libgnutls28-dev
before_script:
    - pip install -U -r modules/profile/files/devrequire.txt

script:
    - pip3 check
    - pip3 freeze
after_script:
    - pipdeptree
notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze-bots"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
