[irc]
    [irc.libera]
    Server="irc.libera.chat:6697"
    Nick="mhbridgebot"
    NickServNick="mh-discord"
    NickServPassword="<%= @discordmhlibera_password %>"
    UseTLS=true
    UseSASL=true
    SkipTLSVerify=false
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    IgnoreNicks="wm-bot"
    JoinDelay=1000

[discord]
    [discord.fosshost]
    Token="<%= @discordfh_token %>"
    Server="Fosshost"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    UseUserName=true

[[gateway]]
    name = "fh.main"
    enable=true

    [[gateway.inout]]
    account = "discord.fosshost"
    channel="ID:742089740643205174"

    [[gateway.inout]]
    account ="irc.libera"
    channel = "#fosshost"

[[gateway]]
    name = "fh.incident"
    enable=true

    [[gateway.inout]]
    account = "discord.fosshost"
    channel="ID:834803116293619803"

    [[gateway.inout]]
    account ="irc.libera"
    channel = "#fosshost-incident"

[[gateway]]
    name = "fh.social"
    enable=true

    [[gateway.inout]]
    account = "discord.fosshost"
    channel="ID:834802993232478248"

    [[gateway.inout]]
    account ="irc.libera"
    channel = "#fosshost-social"

[[gateway]]
    name = "fh.feedback"
    enable=true

    [[gateway.inout]]
    account = "discord.fosshost"
    channel="ID:885275432625262642"

    [[gateway.inout]]
    account ="irc.libera"
    channel = "#fosshost-feedback"
    
[[gateway]]
    name = "fh.acb"
    enable=true
    
    [[gateway.inout]]
    account = "discord.fosshost"
    channel="ID:847535136357875732"
    
    [[gateway.inout]]
    account ="irc.libera"
    channel = "#fosshost-acb"
    
[[gateway]]
    name = "fh.yah"
    enable=true
    
    [[gateway.inout]]
    account = "discord.fosshost"
    channel="ID:898735787603017778"
    
    [[gateway.inout]]
    account ="irc.libera"
    channel = "##yell-at-hammy"
