#!/bin/bash -e
sudo /srv/sopelbots/devvenv/bin/pip3.7 install -U -r /srv/sopelbots/devrequire.txt && cd /srv/sopelbots/devcode/core && sudo rm -rf dist/*.whl build/*.whl && sudo /srv/sopelbots/devvenv/bin/pyproject-build --wheel --outdir dist . && find dist -name "*.whl" | xargs sudo /srv/sopelbots/devvenv/bin/pip3.7 install --no-dependencies

