on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgnutls28-dev
          pip install -U -r modules/profile/files/devrequire.txt
      - name: Run tests
        run: |
          pip3 check
          pip3 freeze
      - name: Run pipdeptree
        run: |
          pipdeptree
